services:
  ros_ws:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
    image: ros_ws:local
    container_name: ros_ws
    privileged: true
    network_mode: host
    gpus: all
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY}
      - IBVS_XFEAT_REPO_DIR=/home/ros_ws/third_party/accelerated_features
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/home/ros_ws
      - ${XAUTHORITY}:${XAUTHORITY}:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    working_dir: /home/ros_ws
    tty: true
    stdin_open: true
    command: bash
